import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:smooth_page_indicator/smooth_page_indicator.dart';

import '../../../../app/routes.dart';
import '../../../../core/constants/app_colors.dart';
import '../../../../core/constants/app_sizes.dart';
import '../../../../core/constants/app_strings.dart';
import '../../../../core/widgets/custom_button.dart';

/// Welcome screen â€” ref: assets/images/welcome_screen.png
///
/// Full-bleed gym background with dark overlay, headline text,
/// "Get Started" (lime) + "Login" (outlined) buttons, page dots, footer.
class WelcomeScreen extends StatefulWidget {
  const WelcomeScreen({super.key});

  @override
  State<WelcomeScreen> createState() => _WelcomeScreenState();
}

class _WelcomeScreenState extends State<WelcomeScreen> {
  final PageController _pageController = PageController();

  // Background pages data
  static const _pages = [
    {
      'headline': 'Your Fitness,\nUnified.',
      'subtitle':
          'The all-in-one ecosystem for members,\ncoaches, and sellers powered by AI.',
    },
    {
      'headline': 'AI-Powered\nWorkouts.',
      'subtitle':
          'Get personalized workout plans\ngenerated by our smart AI engine.',
    },
    {
      'headline': 'Shop & Train\nTogether.',
      'subtitle':
          'Browse fitness products, find coaches,\nand track your progress in one place.',
    },
    {
      'headline': 'Build Your\nFitness Empire.',
      'subtitle':
          'Sell products, coach others, and grow\nyour fitness brand with ease.',
    },
  ];

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        fit: StackFit.expand,
        children: [
          // â”€â”€ Dark gradient background â”€â”€
          Container(
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
                colors: [
                  AppColors.background,
                  Color(0xFF0F1622),
                  Color(0xFF09111B),
                ],
              ),
            ),
          ),
          // â”€â”€ Subtle decorative circles â”€â”€
          Positioned(
            top: -80,
            right: -60,
            child: Container(
              width: 250,
              height: 250,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: RadialGradient(
                  colors: [
                    AppColors.limeGreen.withValues(alpha: 0.08),
                    AppColors.transparent,
                  ],
                ),
              ),
            ),
          ),
          Positioned(
            top: 180,
            left: -70,
            child: Container(
              width: 220,
              height: 220,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: RadialGradient(
                  colors: [
                    AppColors.electricBlue.withValues(alpha: 0.10),
                    AppColors.transparent,
                  ],
                ),
              ),
            ),
          ),
          Positioned(
            bottom: 120,
            left: -80,
            child: Container(
              width: 200,
              height: 200,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: RadialGradient(
                  colors: [
                    AppColors.limeGreen.withValues(alpha: 0.05),
                    AppColors.transparent,
                  ],
                ),
              ),
            ),
          ),

          // â”€â”€ Content â”€â”€
          SafeArea(
            child: Column(
              children: [
                // â”€â”€ Top bar â”€â”€
                Padding(
                  padding: const EdgeInsets.symmetric(
                    horizontal: AppSizes.screenPadding,
                    vertical: AppSizes.lg,
                  ),
                  child: Row(
                    children: [
                      // Logo icon placeholder
                      Container(
                        width: 40,
                        height: 40,
                        decoration: BoxDecoration(
                          gradient: const LinearGradient(
                            colors: [
                              AppColors.limeGreen,
                              AppColors.limeGreenSoft,
                            ],
                          ),
                          borderRadius: BorderRadius.circular(14),
                          boxShadow: [
                            BoxShadow(
                              color: AppColors.limeGreen.withValues(
                                alpha: 0.22,
                              ),
                              blurRadius: 18,
                              offset: Offset(0, 10),
                            ),
                          ],
                        ),
                        alignment: Alignment.center,
                        child: Text(
                          'GU',
                          style: GoogleFonts.spaceGrotesk(
                            fontSize: 14,
                            fontWeight: FontWeight.w700,
                            color: AppColors.black,
                          ),
                        ),
                      ),
                      const SizedBox(width: 10),
                      Text(
                        AppStrings.appName,
                        style: GoogleFonts.spaceGrotesk(
                          fontSize: 20,
                          fontWeight: FontWeight.w700,
                          color: AppColors.textPrimary,
                          letterSpacing: -0.4,
                        ),
                      ),
                      const Spacer(),
                      Container(
                        width: 42,
                        height: 42,
                        decoration: BoxDecoration(
                          color: AppColors.glass,
                          borderRadius: BorderRadius.circular(14),
                          border: Border.all(color: AppColors.borderLight),
                        ),
                        alignment: Alignment.center,
                        child: const Icon(
                          Icons.menu,
                          color: AppColors.textPrimary,
                          size: 22,
                        ),
                      ),
                    ],
                  ),
                ),

                // â”€â”€ PageView for text content â”€â”€
                Expanded(
                  child: PageView.builder(
                    controller: _pageController,
                    itemCount: _pages.length,
                    itemBuilder: (context, index) {
                      final page = _pages[index];
                      return Padding(
                        padding: const EdgeInsets.symmetric(
                          horizontal: AppSizes.screenPadding,
                        ),
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.end,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              padding: const EdgeInsets.symmetric(
                                horizontal: 12,
                                vertical: 8,
                              ),
                              decoration: BoxDecoration(
                                color: AppColors.glass,
                                borderRadius: BorderRadius.circular(999),
                                border: Border.all(
                                  color: AppColors.borderLight,
                                ),
                              ),
                              child: Text(
                                'AI fitness ecosystem',
                                style: GoogleFonts.inter(
                                  fontSize: 11,
                                  fontWeight: FontWeight.w700,
                                  color: AppColors.textSecondary,
                                  letterSpacing: 0.7,
                                ),
                              ),
                            ),
                            const SizedBox(height: 22),
                            Text(
                              page['headline']!,
                              style: GoogleFonts.spaceGrotesk(
                                fontSize: 46,
                                fontWeight: FontWeight.w700,
                                color: AppColors.textPrimary,
                                letterSpacing: -1.0,
                                height: 1.02,
                              ),
                            ),
                            const SizedBox(height: 16),
                            Text(
                              page['subtitle']!,
                              style: GoogleFonts.inter(
                                fontSize: 15,
                                fontWeight: FontWeight.w400,
                                color: AppColors.textSecondary,
                                height: 1.5,
                              ),
                            ),
                            const SizedBox(height: 32),
                          ],
                        ),
                      );
                    },
                  ),
                ),

                // â”€â”€ Buttons â”€â”€
                Padding(
                  padding: const EdgeInsets.symmetric(
                    horizontal: AppSizes.screenPadding,
                  ),
                  child: Container(
                    padding: const EdgeInsets.all(14),
                    decoration: BoxDecoration(
                      color: AppColors.glass,
                      borderRadius: BorderRadius.circular(AppSizes.radiusXxl),
                      border: Border.all(color: AppColors.borderLight),
                    ),
                    child: Column(
                      children: [
                        CustomButton(
                          label: AppStrings.getStarted,
                          onPressed: () {
                            Navigator.pushNamed(
                              context,
                              AppRoutes.roleSelection,
                            );
                          },
                        ),
                        const SizedBox(height: 12),
                        CustomButton(
                          label: AppStrings.login,
                          variant: ButtonVariant.outlined,
                          onPressed: () {
                            Navigator.pushNamed(context, AppRoutes.login);
                          },
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 24),

                // â”€â”€ Page indicator â”€â”€
                SmoothPageIndicator(
                  controller: _pageController,
                  count: _pages.length,
                  effect: ExpandingDotsEffect(
                    dotHeight: 6,
                    dotWidth: 6,
                    activeDotColor: AppColors.limeGreen,
                    dotColor: AppColors.textMuted,
                    expansionFactor: 4,
                  ),
                ),
                const SizedBox(height: 20),

                // â”€â”€ Footer â”€â”€
                Text(
                  AppStrings.revolutionizing,
                  style: GoogleFonts.inter(
                    fontSize: 10,
                    fontWeight: FontWeight.w500,
                    color: AppColors.textMuted,
                    letterSpacing: 2,
                  ),
                ),
                const SizedBox(height: 16),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
