name: my_app
description: "GymUnity — Fitness. AI. Community."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  app_links: ^6.4.1
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  supabase_flutter: ^2.5.4
  flutter_riverpod: ^2.5.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  image: ^4.5.4
  fl_chart: ^0.68.0
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+8
  in_app_purchase_storekit: ^0.4.8+1
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  animations: ^2.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/config/
    - backgrounds/
