// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get settings => 'Settings';

  @override
  String get account => 'Account';

  @override
  String get preferences => 'Preferences';

  @override
  String get support => 'Support';

  @override
  String get accountActions => 'Account Actions';

  @override
  String get retry => 'Retry';

  @override
  String get settingsLoadError =>
      'GymUnity could not load your settings right now.';

  @override
  String get settingsSaveError => 'GymUnity could not save that preference.';

  @override
  String get editProfile => 'Edit Profile';

  @override
  String get coachProfile => 'Coach Profile';

  @override
  String get storeProfile => 'Store Profile';

  @override
  String get adminDashboard => 'Admin Dashboard';

  @override
  String get pushNotifications => 'Push Notifications';

  @override
  String get pushNotificationsSubtitle =>
      'Send key updates outside the app when possible.';

  @override
  String get taiyoSuggestions => 'TAIYO Suggestions';

  @override
  String get taiyoSuggestionsSubtitle =>
      'Highlight new coaching or workout ideas from TAIYO.';

  @override
  String get orderUpdates => 'Order Updates';

  @override
  String get orderUpdatesSubtitle =>
      'Keep store order and delivery status visible in notifications.';

  @override
  String get measurementUnits => 'Measurement Units';

  @override
  String get metric => 'Metric';

  @override
  String get imperial => 'Imperial';

  @override
  String get language => 'Language';

  @override
  String get english => 'English';

  @override
  String get arabic => 'Arabic';

  @override
  String get notificationsCenter => 'Notifications Center';

  @override
  String get helpSupport => 'Help & Support';

  @override
  String get privacyPolicy => 'Privacy Policy';

  @override
  String get termsOfService => 'Terms of Service';

  @override
  String get logOut => 'Log Out';

  @override
  String get logOutQuestion => 'Log out?';

  @override
  String get logoutReturnMessage => 'You will return to the login screen.';

  @override
  String get cancel => 'Cancel';

  @override
  String get deleteAccount => 'Delete Account';

  @override
  String get appVersion => 'GymUnity v1.0.0';

  @override
  String get welcomeEyebrow => 'WELCOME';

  @override
  String get welcomeHeadlineYour => 'Your';

  @override
  String get welcomeHeadlineFitness => 'Fitness,';

  @override
  String get welcomeHeadlineUnified => 'Unified.';

  @override
  String get welcomeSubtitle =>
      'The all-in-one ecosystem for members, coaches, and sellers powered by TAIYO.';

  @override
  String get skip => 'Skip';

  @override
  String get next => 'NEXT';

  @override
  String get poweredByTaiyo => 'POWERED BY TAIYO';

  @override
  String get shopTrainLine1 => 'Shop &';

  @override
  String get shopTrainLine2 => 'Train';

  @override
  String get shopTrainLine3 => 'Together.';

  @override
  String get shopTrainSubtitle =>
      'Browse fitness products, find coaches, and track your progress in one place. A community built on mutual growth.';

  @override
  String get taiyoPowered => 'TAIYO-Powered';

  @override
  String get workouts => 'Workouts.';

  @override
  String get taiyoWorkoutSubtitle =>
      'Get personalized workout plans generated by TAIYO. Designed to adapt to your body\'s rhythm and elevate your sanctuary.';

  @override
  String get buildYour => 'Build Your';

  @override
  String get fitness => 'Fitness';

  @override
  String get empire => 'Empire.';

  @override
  String get fitnessEmpireSubtitle =>
      'Sell products, coach others, and grow your fitness brand with ease. The tools that move with you.';

  @override
  String get continueWithGoogle => 'Continue with Google';

  @override
  String get completingGoogleSignIn => 'Completing Google sign-in...';

  @override
  String get googleOnlyAccess => 'GOOGLE-ONLY ACCESS';

  @override
  String get loginTitle => 'Build Your Fitness Empire.';

  @override
  String get loginSubtitle =>
      'Sell products, coach others, and grow your fitness brand with ease. The tools that move with you.';

  @override
  String get registerTitle => 'Create your account with Google';

  @override
  String get registerSubtitle =>
      'Manual sign-up with name, email, and password has been removed from GymUnity.';

  @override
  String get registerHelper =>
      'Your account is now created automatically after Google sign-in, then GymUnity will continue with role selection and onboarding.';

  @override
  String get backToSignIn => 'Back to sign in';

  @override
  String get forgotPasswordTitle => 'Password reset is no longer used';

  @override
  String get forgotPasswordSubtitle =>
      'GymUnity no longer signs users in with email codes or password reset links.';

  @override
  String get forgotPasswordHelper =>
      'Continue with the Google account linked to your GymUnity profile instead.';

  @override
  String get resetPasswordTitle => 'Password login is disabled';

  @override
  String get resetPasswordSubtitle =>
      'GymUnity now uses Google sign-in only, so reset-password links are no longer part of the app flow.';

  @override
  String get resetPasswordHelper =>
      'Go back to Google sign-in and continue with the Google account linked to GymUnity.';

  @override
  String get completingPasswordRecovery => 'Completing password recovery...';

  @override
  String get googleSignInDidNotComplete =>
      'Google sign-in did not complete. Check Google provider / redirect configuration and try again.';

  @override
  String get passwordRecoveryDidNotComplete =>
      'Password recovery did not complete. Open the latest reset email and try the link again.';

  @override
  String get passwordRecovery => 'Password Recovery';

  @override
  String providerSignIn(String provider) {
    return '$provider Sign-In';
  }

  @override
  String get passwordRecoveryVerifying =>
      'Please wait while GymUnity verifies your password recovery request.';

  @override
  String get accountLinkingWait =>
      'Please wait while GymUnity links your account and restores your session.';

  @override
  String get backToLogin => 'Back to Login';

  @override
  String get roleHeadline => 'Join the Movement as a...';

  @override
  String get roleSubtitle => 'Choose your role to start your fitness journey';

  @override
  String get roleProductionSubtitle =>
      'Choose your member experience to continue into GymUnity.';

  @override
  String get member => 'Member';

  @override
  String get memberDesc =>
      'Access personalized workouts, shop the store, and connect with elite coaches.';

  @override
  String get memberCta => 'Get Started Today';

  @override
  String get popular => 'POPULAR';

  @override
  String get seller => 'Seller';

  @override
  String get sellerDesc =>
      'Sell your fitness products, manage inventory, and grow your brand globally.';

  @override
  String get sellerCta => 'Grow Business';

  @override
  String get coach => 'Coach';

  @override
  String get coachDesc =>
      'Manage your clients, sell professional training plans, and track progress.';

  @override
  String get coachCta => 'Empower Others';

  @override
  String get select => 'Select';

  @override
  String get alreadyHaveAccount => 'Already have an account?';

  @override
  String get logIn => 'Log in';

  @override
  String get unableSaveRole => 'Unable to save your role right now.';

  @override
  String get goalSetup => 'Goal setup';

  @override
  String get memberGoalTitle => 'What result do you want first?';

  @override
  String get memberGoalSubtitle =>
      'We tune coaches, offers, and check-ins toward the outcome you choose.';

  @override
  String get loseWeight => 'Lose Weight';

  @override
  String get loseWeightDesc =>
      'Fat loss, simpler food habits, and weekly accountability.';

  @override
  String get buildMuscle => 'Build Muscle';

  @override
  String get buildMuscleDesc =>
      'Lean mass, better training structure, and recovery.';

  @override
  String get recompose => 'Recompose';

  @override
  String get recomposeDesc => 'Lose fat while improving shape and consistency.';

  @override
  String get generalFitness => 'General Fitness';

  @override
  String get generalFitnessDesc =>
      'Energy, movement, and sustainable habits that stick.';

  @override
  String get baseline => 'Baseline';

  @override
  String get memberBaselineTitle => 'Tell us where you are now';

  @override
  String get memberBaselineSubtitle =>
      'This shapes progress tracking, coach recommendations, and your first check-in baseline.';

  @override
  String get gender => 'Gender';

  @override
  String get male => 'Male';

  @override
  String get female => 'Female';

  @override
  String get height => 'Height';

  @override
  String get weight => 'Weight';

  @override
  String get age => 'Age';

  @override
  String get city => 'City';

  @override
  String get heightHint => 'e.g. 170';

  @override
  String get weightHint => 'e.g. 82';

  @override
  String get ageHint => 'e.g. 26';

  @override
  String get cityHint => 'e.g. Cairo';

  @override
  String get coachMatch => 'Coach match';

  @override
  String get memberCoachMatchTitle => 'What kind of coaching fits your life?';

  @override
  String get memberCoachMatchSubtitle =>
      'These inputs tune pricing, language, and delivery filters in the marketplace.';

  @override
  String get monthlyBudget => 'Monthly budget';

  @override
  String get budgetHint => 'e.g. 1500';

  @override
  String get coachingMode => 'Coaching mode';

  @override
  String get online => 'Online';

  @override
  String get inPerson => 'In person';

  @override
  String get hybrid => 'Hybrid';

  @override
  String get trainingPlace => 'Training place';

  @override
  String get home => 'Home';

  @override
  String get gym => 'Gym';

  @override
  String get both => 'Both';

  @override
  String get preferredLanguage => 'Preferred language';

  @override
  String get preferredCoachGender => 'Preferred coach gender';

  @override
  String get any => 'Any';

  @override
  String get trainingRhythm => 'Training rhythm';

  @override
  String get memberTrainingTitle => 'How ready are you to commit each week?';

  @override
  String get memberTrainingSubtitle =>
      'We use this to set realistic accountability and starter plan expectations.';

  @override
  String get experienceLevel => 'Experience level';

  @override
  String get beginner => 'Beginner';

  @override
  String get intermediate => 'Intermediate';

  @override
  String get advanced => 'Advanced';

  @override
  String get athlete => 'Athlete';

  @override
  String get weeklyFrequency => 'Weekly frequency';

  @override
  String get oneTwoDays => '1-2 days/week';

  @override
  String get threeFourDays => '3-4 days/week';

  @override
  String get fiveSixDays => '5-6 days/week';

  @override
  String get everyDay => 'Every day';

  @override
  String get continueAction => 'CONTINUE';

  @override
  String get getStarted => 'GET STARTED';

  @override
  String stepOfTotal(int step, int totalSteps) {
    return 'STEP $step OF $totalSteps';
  }

  @override
  String get chooseGoalToContinue => 'Choose a goal to continue.';

  @override
  String get chooseGenderToContinue => 'Choose your gender to continue.';

  @override
  String get enterRealisticHeight => 'Enter a realistic height in centimeters.';

  @override
  String get enterRealisticWeight => 'Enter a realistic weight in kilograms.';

  @override
  String get enterValidAge => 'Enter a valid age between 13 and 100.';

  @override
  String get addCity =>
      'Add your city so we can match you with the right coaches.';

  @override
  String get addBudget => 'Add a realistic monthly budget in EGP.';

  @override
  String get chooseCoachingMode =>
      'Choose the coaching mode that fits you best.';

  @override
  String get chooseTrainingPlace => 'Choose where you plan to train.';

  @override
  String get choosePreferredCoachingLanguage =>
      'Choose your preferred coaching language.';

  @override
  String get choosePreferredCoachGender =>
      'Choose your preferred coach gender.';

  @override
  String get chooseExperience => 'Choose your current experience level.';

  @override
  String get chooseFrequency => 'Choose your weekly training frequency.';

  @override
  String get completeOnboarding =>
      'Complete each onboarding step before getting started.';

  @override
  String get unableCompleteOnboarding =>
      'Unable to complete onboarding right now.';

  @override
  String get goalFooter =>
      'Choose the goal that best matches your current fitness priority. You can update it later.';

  @override
  String get baselineFooter =>
      'Your baseline drives weight, waist, and progress check-ins later.';

  @override
  String get matchFooter =>
      'These preferences directly shape the coach marketplace filters and pricing shown first.';

  @override
  String get trainingFooter =>
      'You can update these choices later from your profile and settings.';

  @override
  String get beginnerHelper =>
      'You need simple instructions and closer follow-up.';

  @override
  String get intermediateHelper =>
      'You train already, but want better structure and feedback.';

  @override
  String get advancedHelper =>
      'You can handle more load, volume, and tighter planning.';

  @override
  String get athleteHelper =>
      'Performance-first training with serious consistency.';

  @override
  String get oneTwoDaysHelper => 'Low-friction routine focused on momentum.';

  @override
  String get threeFourDaysHelper =>
      'Balanced pace for visible progress and recovery.';

  @override
  String get fiveSixDaysHelper =>
      'High-consistency track with structured recovery.';

  @override
  String get everyDayHelper =>
      'Best for very committed routines with coach oversight.';

  @override
  String get statusInProgress => 'In progress';

  @override
  String get statusPending => 'Pending';

  @override
  String get statusCompleted => 'Completed';

  @override
  String get statusPartial => 'Partial';

  @override
  String get statusSkipped => 'Skipped';

  @override
  String get statusMissed => 'Missed';

  @override
  String get statusActive => 'Active';

  @override
  String get statusArchived => 'Archived';

  @override
  String get statusPublished => 'Published';

  @override
  String get statusDraft => 'Draft';

  @override
  String get riskLow => 'Low';

  @override
  String get riskMedium => 'Medium';

  @override
  String get riskHigh => 'High';
}
